version: '3.8'

services:
  server:
    container_name: esp-server
    build: .
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./app.js:/app/app.js
    environment:
      - TZ=Asia/Ho_Chi_Minh
    command: bun run dev
    depends_on:
      - frontend

  frontend:
    container_name: esp-frontend
    build:
      context: ./frontend
      dockerfile: dockerfile-dev
    ports:
      - "80:5173"
    volumes:
      - ./frontend/src:/app/src
    restart: always