name: Build frontend (bun) and push to release

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ⚠️ rất quan trọng

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install deps
        working-directory: frontend
        run: bun install

      - name: Build frontend
        working-directory: frontend
        run: bun run build

      - name: Prepare release content
        run: |
          rm -rf release_tmp
          mkdir -p release_tmp/src/frontend
          cp -r frontend/dist/* release_tmp/src/frontend/
          cp app.js package.json release_tmp/

      - name: Push to release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "lybaocuong@gmail.com"

          git checkout --orphan release
          git rm -rf .

          cp -r release_tmp/* .

          git add .
          git commit -m "build frontend (bun)"
          git push -f https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git release
